[2025-07-19T02:55:21.847+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T02:55:21.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T02:50:00+00:00 [queued]>
[2025-07-19T02:55:21.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T02:50:00+00:00 [queued]>
[2025-07-19T02:55:21.897+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-19T02:55:21.914+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dvc_add_data> on 2025-07-19 02:50:00+00:00
[2025-07-19T02:55:21.933+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-19T02:55:21.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ferry_portfolio_etl', 'dvc_add_data', 'scheduled__2025-07-19T02:50:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ferry_pipeline_dag.py', '--cfg-path', '/tmp/tmpq6wipmmk']
[2025-07-19T02:55:21.936+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2025-07-19T02:55:21.936+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dvc_add_data
[2025-07-19T02:55:21.956+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-19T02:55:22.020+0000] {task_command.py:426} INFO - Running <TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T02:50:00+00:00 [running]> on host e6373d0838bd
[2025-07-19T02:55:22.128+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='ferry_portfolio_etl' AIRFLOW_CTX_TASK_ID='dvc_add_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T02:50:00+00:00'
[2025-07-19T02:55:22.129+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T02:55:23.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T02:55:23.660+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ferry_pipeline_dag.py", line 12, in run_dvc_add
    subprocess.run(["dvc", "add", data_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dvc', 'add', 'artifacts\x0cerry_raw.csv']' returned non-zero exit status 255.
[2025-07-19T02:55:23.683+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ferry_portfolio_etl, task_id=dvc_add_data, run_id=scheduled__2025-07-19T02:50:00+00:00, execution_date=20250719T025000, start_date=20250719T025521, end_date=20250719T025523
[2025-07-19T02:55:23.705+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dvc_add_data (Command '['dvc', 'add', 'artifacts\x0cerry_raw.csv']' returned non-zero exit status 255.; 293)
[2025-07-19T02:55:23.761+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-19T02:55:23.792+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T02:55:23.798+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
