[2025-07-19T16:41:31.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T16:41:31.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T16:30:00+00:00 [queued]>
[2025-07-19T16:41:31.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T16:30:00+00:00 [queued]>
[2025-07-19T16:41:31.827+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-19T16:41:31.842+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dvc_add_data> on 2025-07-19 16:30:00+00:00
[2025-07-19T16:41:31.873+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-19T16:41:31.875+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2025-07-19T16:41:31.873+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ferry_portfolio_etl', 'dvc_add_data', 'scheduled__2025-07-19T16:30:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/ferry_pipeline_dag.py', '--cfg-path', '/tmp/tmpa9knhzv9']
[2025-07-19T16:41:31.877+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask dvc_add_data
[2025-07-19T16:41:31.902+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-19T16:41:32.030+0000] {task_command.py:426} INFO - Running <TaskInstance: ferry_portfolio_etl.dvc_add_data scheduled__2025-07-19T16:30:00+00:00 [running]> on host c9c2eb7162c9
[2025-07-19T16:41:32.205+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='ferry_portfolio_etl' AIRFLOW_CTX_TASK_ID='dvc_add_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T16:30:00+00:00'
[2025-07-19T16:41:32.207+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T16:41:32.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T16:41:32.260+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ferry_pipeline_dag.py", line 46, in run_dvc_add
    raise FileNotFoundError(f"{data_path} not found!")
FileNotFoundError: artifacts/ferry_raw.csv not found!
[2025-07-19T16:41:32.282+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ferry_portfolio_etl, task_id=dvc_add_data, run_id=scheduled__2025-07-19T16:30:00+00:00, execution_date=20250719T163000, start_date=20250719T164131, end_date=20250719T164132
[2025-07-19T16:41:32.307+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 186 for task dvc_add_data (artifacts/ferry_raw.csv not found!; 176)
[2025-07-19T16:41:32.333+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-19T16:41:32.370+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T16:41:32.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
