[2025-07-18T20:25:01.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T20:25:01.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-18T20:20:00+00:00 [queued]>
[2025-07-18T20:25:01.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-18T20:20:00+00:00 [queued]>
[2025-07-18T20:25:01.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-18T20:25:01.844+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-18 20:20:00+00:00
[2025-07-18T20:25:01.899+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-18T20:25:01.905+0000] {standard_task_runner.py:63} INFO - Started process 345 to run task
[2025-07-18T20:25:01.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ferry_portfolio_etl', 'extract_data', 'scheduled__2025-07-18T20:20:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ferry_pipeline_dag.py', '--cfg-path', '/tmp/tmpc4thctfz']
[2025-07-18T20:25:01.963+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask extract_data
[2025-07-18T20:25:02.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-18T20:25:02.366+0000] {task_command.py:426} INFO - Running <TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-18T20:20:00+00:00 [running]> on host 41c60911f097
[2025-07-18T20:25:02.536+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='ferry_portfolio_etl' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T20:20:00+00:00'
[2025-07-18T20:25:02.543+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T20:25:02.577+0000] {extract_data.py:78} INFO - üöÄ Starting ferry data extraction pipeline...
[2025-07-18T20:25:10.496+0000] {extract_data.py:80} INFO - üìä Retrieved 100000 rows and 4 columns
[2025-07-18T20:25:10.715+0000] {extract_data.py:19} INFO - ‚úÖ Saved temporary file for DVC: artifacts/ferry_raw.csv
[2025-07-18T20:25:10.716+0000] {extract_data.py:28} INFO - ü™£ Uploading file to S3: s3://ashok-ferry-data-bucket/raw_data/raw.csv
[2025-07-18T20:25:11.124+0000] {extract_data.py:37} ERROR - ‚ùå Error uploading to S3: Unable to locate credentials
[2025-07-18T20:25:11.125+0000] {extract_data.py:98} ERROR - üö® Failed in extract_data pipeline: CustomException.__init__() missing 1 required positional argument: 'error_details'
[2025-07-18T20:25:11.132+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-18T20:25:11.133+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T20:25:11.145+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ferry_portfolio_etl, task_id=extract_data, run_id=scheduled__2025-07-18T20:20:00+00:00, execution_date=20250718T202000, start_date=20250718T202501, end_date=20250718T202511
[2025-07-18T20:25:11.191+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-18T20:25:11.239+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-18T20:25:11.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
